name: Wokwi CI Tests

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [test_1, test_2, test_3]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test with Wokwi
      uses: wokwi/wokwi-ci-action@v1
      with:
        token: ${{ secrets.WOKWI_CLI_TOKEN }}
        scenario: 'scenarios/light/${{ matrix.test_type }}.yaml'
        timeout: 10000